version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./packages/server/prisma/dev.db:/app/prisma/dev.db
    environment:
      - DB_PATH=/app/prisma/dev.db
      - DATABASE_URL=file:/app/prisma/dev.db
    restart: always

#  client:
#    build:
#      context: .
#      dockerfile: packages/client/Dockerfile
#    ports:
#      - "5173:5173"
